import { Inter } from 'next/font/google';
import './globals.css';
import HeaderPage from './components/HeaderPage';
import FooterPage from './components/FooterPage';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body
        className={`${inter.className} bg-main-bg `}
        suppressHydrationWarning={true}
      >
        <HeaderPage />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
